# version: '3'
# services:
#   task-manager:
#     image: task-manager:1.0
#     ports:
#     - 3000:3000
#   mongodb:
#     image: mongo
#     ports:  
#     - 27017:27017
#     environment:
#       - MONGO_INITDB_DATABASE=mydb
#   mongo-express:
#     image: mongo-express
#     ports: 
#     - 8081:8081
#     environment:
#       ME_CONFIG_MONGODB_SERVER: mongo

services:
  task-manager:
    image: task-manager:1.0
    ports:
      - 3000:3000
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password